# Generated by Django 4.2.4 on 2023-11-27 11:35

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='placementapp.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placementapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=50)),
                ('jobcode', models.CharField(max_length=200)),
                ('Vacancies', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others'), ('both', 'both')], max_length=300, verbose_name='Gender')),
                ('description', models.CharField(max_length=50)),
                ('Salary', models.CharField(max_length=50)),
                ('Last_date', models.DateField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placementapp.course')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
            ],
        ),
    ]
