# Generated by Django 4.2.4 on 2023-11-27 11:35

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Work_Experience', models.CharField(choices=[('Fresher', 'Fresher'), ('1-3 years', '1-3 years'), ('4-7 years', '4-7 years'), ('8+ years', '8+ years')], max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='upload_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('resume', models.FileField(blank=True, null=True, upload_to='upload_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=300, verbose_name='Gender')),
                ('Address', models.TextField()),
                ('phoneNumber', models.CharField(max_length=50)),
                ('verify', models.BooleanField(default=False)),
                ('batch', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='course', chained_model_field='course', on_delete=django.db.models.deletion.CASCADE, to='placementapp.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placementapp.course')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placementapp.qualification')),
                ('trainer', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='batch', chained_model_field='batch', on_delete=django.db.models.deletion.CASCADE, to='placementapp.trainer')),
            ],
        ),
    ]
